=== Khmelov/JD2018-12-10/src/by/it/subach/jd02_07/internet_store/orders/Orders.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT orders (order)+>
<!ELEMENT order (number, date, client, goods, paymentstatus)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT client (#PCDATA)>
<!ELEMENT goods (good)>
<!ELEMENT good (name, quantity)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT paymentstatus (#PCDATA)>

=== Khmelov/JD2018-12-10/src/by/it/subach/jd02_07/internet_store/orders/Orders+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE orders SYSTEM "Orders.dtd">
<orders>
    <order>
        <number>1</number>
        <date>10.02.2019</date>
        <client>CarlCracker</client>
        <goods>
            <good>
                <name>PlayStation5</name>
                <quantity>2</quantity>
            </good>
        </goods>
        <paymentstatus>not paid</paymentstatus>
    </order>
    <order>
        <number>2</number>
        <date>11.02.2019</date>
        <client>ClintEastwood</client>
        <goods>
            <good>
                <name>XboxTWO</name>
                <quantity>1</quantity>
            </good>
        </goods>
        <paymentstatus>paid</paymentstatus>
    </order>
    <order>
        <number>2</number>
        <date>11.02.2019</date>
        <client>AngelinaJolie</client>
        <goods>
            <good>
                <name>NintendoWOO</name>
                <quantity>3</quantity>
            </good>
        </goods>
        <paymentstatus>paid</paymentstatus>
    </order>
</orders>
