=== Khmelov/JD2018-12-10/src/by/it/subach/jd02_07/internet_store/clients/Clients.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT clients (client)+>
<!ELEMENT client (login, email, password, telnumber, adress)>
<!ELEMENT login (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT telnumber (#PCDATA)>
<!ELEMENT adress (city, street, house, apart, postalindex)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT house (#PCDATA)>
<!ELEMENT apart (#PCDATA)>
<!ELEMENT postalindex (#PCDATA)>

=== Khmelov/JD2018-12-10/src/by/it/subach/jd02_07/internet_store/clients/Clients+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE clients SYSTEM "Clients.dtd">
<clients>
    <client>
        <login>CarlCracker</login>
        <email>carlcracker@gmail.com</email>
        <password>12345</password>
        <telnumber>375291112233</telnumber>
        <adress>
            <city>Minsk</city>
            <street>Lenina</street>
            <house>1</house>
            <apart>18</apart>
            <postalindex>220011</postalindex>
        </adress>
    </client>
    <client>
        <login>ClintEastwood</login>
        <email>eastwood@gmail.com</email>
        <password>qwerty</password>
        <telnumber>375292223344</telnumber>
        <adress>
            <city>Babruisk</city>
            <street>Marksa</street>
            <house>6A</house>
            <apart>28</apart>
            <postalindex>281263</postalindex>
        </adress>
    </client>
    <client>
        <login>AngelinaJolie</login>
        <email>angela@gmail.com</email>
        <password>asdfg</password>
        <telnumber>375296662255</telnumber>
        <adress>
            <city>Orsha</city>
            <street>Engelsa</street>
            <house>12</house>
            <apart>6</apart>
            <postalindex>294518</postalindex>
        </adress>
    </client>
</clients>
