=== Khmelov/JD2018-12-10/src/by/it/zagurskaya/jd02_07/users.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT users (user)+>
<!ELEMENT user (idUser,login,password,description)>
<!ELEMENT idUser (#PCDATA)>
<!ELEMENT login (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT description (operations,kassa,duties)+>
<!ELEMENT operations (operation)+>
<!ELEMENT operation (idOperation, nameOperation, printForm, skreanForm,specification, entrys)>
<!ELEMENT idOperation (#PCDATA)>
<!ELEMENT nameOperation (#PCDATA)>
<!ELEMENT printForm (#PCDATA)>
<!ELEMENT skreanForm (#PCDATA)>
<!ELEMENT specification (#PCDATA)>
<!ELEMENT entrys (entry)+>
<!ELEMENT entry (idEntry, nameEntry, currencyEntry, accauntDebitEntry, accauntKreditEntry,sumEntry,comingOrSpeting,rateEntry)>
<!ELEMENT idEntry (#PCDATA)>
<!ELEMENT nameEntry (#PCDATA)>
<!ELEMENT currencyEntry (#PCDATA)>
<!ELEMENT accauntDebitEntry (#PCDATA)>
<!ELEMENT accauntKreditEntry (#PCDATA)>
<!ELEMENT sumEntry (#PCDATA)>
<!ELEMENT comingOrSpeting (#PCDATA)>
<!ELEMENT rateEntry (#PCDATA)>
<!ELEMENT kassa (currencys)>
<!ELEMENT currencys (currency)+>
<!ELEMENT currency (idCurrency,receivedCurrency,comingCurrency, spendingCurrency,hendedCurrency,balanceCarrency)+>
<!ELEMENT idCurrency (#PCDATA)>
<!ELEMENT receivedCurrency (#PCDATA)>
<!ELEMENT comingCurrency (#PCDATA)>
<!ELEMENT spendingCurrency (#PCDATA)>
<!ELEMENT hendedCurrency (#PCDATA)>
<!ELEMENT balanceCarrency (#PCDATA)>
<!ELEMENT duties (idDuties,idUser,appno,dateDuties,numberDuties,open1OrClose2)+>
<!ELEMENT idDuties (#PCDATA)>
<!ELEMENT appno (#PCDATA)>
<!ELEMENT dateDuties (#PCDATA)>
<!ELEMENT numberDuties (#PCDATA)>
<!ELEMENT open1OrClose2 (#PCDATA)>

=== Khmelov/JD2018-12-10/src/by/it/zagurskaya/jd02_07/users+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE users SYSTEM "users.dtd" >
<users>
    <user>
        <idUser>5</idUser>
        <login>IvanovaVP</login>
        <password>qwerty</password>
        <description>
            <operations>
                <operation>
                    <idOperation>1000</idOperation>
                    <nameOperation>Подкрепление</nameOperation>
                    <printForm>1000</printForm>
                    <skreanForm>1000</skreanForm>
                    <specification>Получены денежные средства</specification>
                    <entrys>
                        <entry>
                            <idEntry> 100001</idEntry>
                            <nameEntry>Получено валюты</nameEntry>
                            <currencyEntry>840</currencyEntry>
                            <accauntDebitEntry> </accauntDebitEntry>
                            <accauntKreditEntry>1010000000005</accauntKreditEntry>
                            <sumEntry>1000</sumEntry>
                            <comingOrSpeting>0</comingOrSpeting>
                            <rateEntry>2.1</rateEntry>
                        </entry>
                        <entry>
                            <idEntry> 100002</idEntry>
                            <nameEntry>Получено рублей</nameEntry>
                            <currencyEntry>933</currencyEntry>
                            <accauntDebitEntry> </accauntDebitEntry>
                            <accauntKreditEntry>1010000000005</accauntKreditEntry>
                            <sumEntry>1000</sumEntry>
                            <comingOrSpeting>0</comingOrSpeting>
                            <rateEntry>1</rateEntry>
                        </entry>
                    </entrys>
                </operation>
                <operation>
                    <idOperation>10</idOperation>
                    <nameOperation>Покупка валюты</nameOperation>
                    <printForm>10</printForm>
                    <skreanForm>10</skreanForm>
                    <specification>В личное пользование </specification>
                    <entrys>
                        <entry>
                            <idEntry> 1001</idEntry>
                            <nameEntry>Покупка валюты</nameEntry>
                            <currencyEntry>840</currencyEntry>
                            <accauntDebitEntry>1010000000005</accauntDebitEntry>
                            <accauntKreditEntry>6901000000840</accauntKreditEntry>
                            <sumEntry>100</sumEntry>
                            <comingOrSpeting>0</comingOrSpeting>
                            <rateEntry>2.1</rateEntry>
                        </entry>
                        <entry>
                            <idEntry> 1002</idEntry>
                            <nameEntry>Рублевый эквивалент</nameEntry>
                            <currencyEntry>933</currencyEntry>
                            <accauntDebitEntry>6911000000840</accauntDebitEntry>
                            <accauntKreditEntry>1010000000005</accauntKreditEntry>
                            <sumEntry>210</sumEntry>
                            <comingOrSpeting>1</comingOrSpeting>
                            <rateEntry>1</rateEntry>
                        </entry>
                    </entrys>
                </operation>
                <operation>
                    <idOperation>998</idOperation>
                    <nameOperation>Коммунальный платеж</nameOperation>
                    <printForm>998</printForm>
                    <skreanForm>998</skreanForm>
                    <specification> За питание в СД№3 </specification>
                    <entrys>
                        <entry>
                            <idEntry> 99801</idEntry>
                            <nameEntry>Приход денежных средст в кассу</nameEntry>
                            <currencyEntry>933</currencyEntry>
                            <accauntDebitEntry>1010000000005</accauntDebitEntry>
                            <accauntKreditEntry>3819000000000</accauntKreditEntry>
                            <sumEntry>56</sumEntry>
                            <comingOrSpeting>0</comingOrSpeting>
                            <rateEntry>1</rateEntry>
                        </entry>
                    </entrys>
                </operation>
            </operations>
            <kassa>
                <currencys>
                    <currency>
                        <idCurrency>840</idCurrency>
                        <receivedCurrency>1000</receivedCurrency>
                        <comingCurrency>100</comingCurrency>
                        <spendingCurrency>0</spendingCurrency>
                        <hendedCurrency>0</hendedCurrency>
                        <balanceCarrency>1100</balanceCarrency>
                    </currency>
                    <currency>
                        <idCurrency>933</idCurrency>
                        <receivedCurrency>1000</receivedCurrency>
                        <comingCurrency>100</comingCurrency>
                        <spendingCurrency>210</spendingCurrency>
                        <hendedCurrency>0</hendedCurrency>
                        <balanceCarrency>690</balanceCarrency>
                    </currency>
                </currencys>
            </kassa>
            <duties>
                <idDuties>1</idDuties>
                <idUser>5</idUser>
                <appno>15703</appno>
                <dateDuties>01/01/2019</dateDuties>
                <numberDuties>1</numberDuties>
                <open1OrClose2>1</open1OrClose2>
            </duties>
        </description>
    </user>
    <user>
        <idUser>6</idUser>
        <login>PetrovaTI</login>
        <password>qazwsx</password>
        <description>
            <operations>
                <operation>
                    <idOperation>1000</idOperation>
                    <nameOperation>Подкрепление</nameOperation>
                    <printForm>1000</printForm>
                    <skreanForm>1000</skreanForm>
                    <specification> Получены денежные средства</specification>
                    <entrys>
                        <entry>
                            <idEntry> 100001</idEntry>
                            <nameEntry>Получено валюты</nameEntry>
                            <currencyEntry>840</currencyEntry>
                            <accauntDebitEntry> </accauntDebitEntry>
                            <accauntKreditEntry>1010000000005</accauntKreditEntry>
                            <sumEntry>1000</sumEntry>
                            <comingOrSpeting>0</comingOrSpeting>
                            <rateEntry>2.1</rateEntry>
                        </entry>
                        <entry>
                            <idEntry> 100002</idEntry>
                            <nameEntry>Получено рублей</nameEntry>
                            <currencyEntry>933</currencyEntry>
                            <accauntDebitEntry> </accauntDebitEntry>
                            <accauntKreditEntry>1010000000005</accauntKreditEntry>
                            <sumEntry>1000</sumEntry>
                            <comingOrSpeting>0</comingOrSpeting>
                            <rateEntry>1</rateEntry>
                        </entry>
                    </entrys>
                </operation>
                <operation>
                    <idOperation>20</idOperation>
                    <nameOperation>Продажа валюты</nameOperation>
                    <printForm>20</printForm>
                    <skreanForm>20</skreanForm>
                    <specification> В личное пользование</specification>
                    <entrys>
                        <entry>
                            <idEntry> 2001</idEntry>
                            <nameEntry>Продажа валюты</nameEntry>
                            <currencyEntry>840</currencyEntry>
                            <accauntDebitEntry>6901000000840</accauntDebitEntry>
                            <accauntKreditEntry>1010000000000</accauntKreditEntry>
                            <sumEntry>200</sumEntry>
                            <comingOrSpeting>1</comingOrSpeting>
                            <rateEntry>2.15</rateEntry>
                        </entry>
                        <entry>
                            <idEntry> 2002</idEntry>
                            <nameEntry>Рублевый эквивалент</nameEntry>
                            <currencyEntry>933</currencyEntry>
                            <accauntDebitEntry>1010000000000</accauntDebitEntry>
                            <accauntKreditEntry>6911000000840</accauntKreditEntry>
                            <sumEntry>430</sumEntry>
                            <comingOrSpeting>0</comingOrSpeting>
                            <rateEntry>1</rateEntry>
                        </entry>
                    </entrys>
                </operation>
                <operation>
                    <idOperation>998</idOperation>
                    <nameOperation>Коммунальный платеж</nameOperation>
                    <printForm>998</printForm>
                    <skreanForm>998</skreanForm>
                    <specification> За мобильный телефор</specification>
                    <entrys>
                        <entry>
                            <idEntry> 99801</idEntry>
                            <nameEntry>Приход денежных средст в кассу</nameEntry>
                            <currencyEntry>933</currencyEntry>
                            <accauntDebitEntry>1010000000005</accauntDebitEntry>
                            <accauntKreditEntry>3819000000000</accauntKreditEntry>
                            <sumEntry>20</sumEntry>
                            <comingOrSpeting>0</comingOrSpeting>
                            <rateEntry>1</rateEntry>
                        </entry>
                    </entrys>
                </operation>
