=== Khmelov/JD2018-12-10/src/by/it/subach/jd02_07/internet_store/admins/Admins.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it-academy.by/it/subach/jd02_07/admins"
        xmlns:mytype="http://it-academy.by/it/subach/jd02_07/admins"
        elementFormDefault="qualified"
>
    <element name="admins">
        <complexType>
            <sequence>
                <element name="admin"
                         type="mytype:admintype"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="admintype">
        <sequence>
            <element name="login" type="ID"/>
            <element name="email" type="string"/>
            <element name="password" type="string"/>
        </sequence>
    </complexType>

</schema>

=== Khmelov/JD2018-12-10/src/by/it/subach/jd02_07/internet_store/admins/Admins+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<admins     xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://it-academy.by/it/subach/jd02_07/admins"
            xsi:schemaLocation="http://it-academy.by/it/subach/jd02_07/admins admins.xsd"
>
    <admin>
        <login>Alfons</login>
        <email>alfons@gmail.com</email>
        <password>123456</password>
    </admin>

    <admin>
        <login>Andrey</login>
        <email>andrey@gmail.com</email>
        <password>qwerty</password>
    </admin>

</admins>
