=== Khmelov/JD2018-12-10/src/by/it/subach/jd02_07/internet_store/catalog/Catalog.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it-academy.by/it/subach/jd02_07/catalog"
        elementFormDefault="qualified"
>
    <element name="catalog">
        <complexType>
            <sequence>
                <element name="consoles">
                    <complexType>
                        <sequence>
                            <element name="console"
                                     minOccurs="1"
                                     maxOccurs="unbounded"
                                     >
                                <complexType>
                                    <sequence>
                                        <element type="string" name="name"/>
                                        <element type="string" name="discription"/>
                                        <element type="float" name="price"/>
                                        <element type="float" name="weight"/>
                                        <element type="positiveInteger" name="quantity"/>
                                        <element type="string" name="manufacturer"/>
                                    </sequence>
                                </complexType>
                            </element>
                            
                        </sequence>
                    </complexType>
                </element>

            </sequence>
        </complexType>
    </element>
</schema>

=== Khmelov/JD2018-12-10/src/by/it/subach/jd02_07/internet_store/catalog/Catalog+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<catalog    xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://it-academy.by/it/subach/jd02_07/catalog"
            xsi:schemaLocation="http://it-academy.by/it/subach/jd02_07/catalog Catalog.xsd"
>
    <consoles>
        <console>
            <name>PlayStation5</name>
            <discription>Number one in the world</discription>
            <price>500.00</price>
            <weight>3.2</weight>
            <quantity>10</quantity>
            <manufacturer>Sony</manufacturer>
        </console>
        <console>
            <name>XboxTWO</name>
            <discription>Number two in the world</discription>
            <price>600.00</price>
            <weight>4</weight>
            <quantity>5</quantity>
            <manufacturer>Microsoft</manufacturer>
        </console>
        <console>
            <name>NintendoWoo</name>
            <discription>Number three in the world</discription>
            <price>400.00</price>
            <weight>2</weight>
            <quantity>7</quantity>
            <manufacturer>Nintendo</manufacturer>
        </console>
    </consoles>
</catalog>
