=== Khmelov/JD2018-12-10/src/by/it/titkovskaya/jd02_07/clients.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT clients (client)+>
        <!ELEMENT client (client_ID,name,passport,login,password,accounts)>
        <!ELEMENT client_ID (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT passport (#PCDATA)>
        <!ELEMENT login (#PCDATA)>
        <!ELEMENT password (#PCDATA)>
        <!ELEMENT accounts (account)+>
        <!ELEMENT account (account_ID,authorization_code,account_balance,currency,last_replenishment,last_payment,status,lock_date)>
        <!ELEMENT account_ID (#PCDATA)>
        <!ELEMENT authorization_code (#PCDATA)>
        <!ELEMENT account_balance (#PCDATA)>
        <!ELEMENT currency (#PCDATA)>
        <!ELEMENT last_replenishment (replenishment_amount,replenishment_date)>
        <!ELEMENT replenishment_amount (#PCDATA)>
        <!ELEMENT replenishment_date (#PCDATA)>
        <!ELEMENT last_payment (payment_amount,payment_date)>
        <!ELEMENT payment_amount (#PCDATA)>
        <!ELEMENT payment_date (#PCDATA)>
        <!ELEMENT status (#PCDATA)>
        <!ELEMENT lock_date (#PCDATA)>

=== Khmelov/JD2018-12-10/src/by/it/titkovskaya/jd02/jd02_07/clients+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE clients SYSTEM
        "C:\Users\Airina\Documents\java development\JD2018-12-10\src\by\it\titkovskaya\jd02_07\clients.dtd">

<clients>
    <client>
        <client_ID>123456789AB</client_ID>
        <name>
            John Smith
        </name>
        <passport>MP1234567</passport>
        <login>johnSMITH</login>
        <password>12345</password>
        <accounts>
            <account>
                <account_ID>123456789</account_ID>
                <authorization_code>6789</authorization_code>
                <account_balance>1000</account_balance>
                <currency>USD</currency>
                <last_replenishment>
                    <replenishment_amount>100</replenishment_amount>
                    <replenishment_date>01.01.2019</replenishment_date>
                </last_replenishment>
                <last_payment>
                    <payment_amount>200</payment_amount>
                    <payment_date>02.02.2019</payment_date>
                </last_payment>
                <status>active</status>
                <lock_date>-</lock_date>
            </account>
            <account>
                <account_ID>567891234</account_ID>
                <authorization_code>1234</authorization_code>
                <account_balance>0</account_balance>
                <currency>BYN</currency>
                <last_replenishment>
                    <replenishment_amount>10000</replenishment_amount>
                    <replenishment_date>10.01.2019</replenishment_date>
                </last_replenishment>
                <last_payment>
                    <payment_amount>30000</payment_amount>
                    <payment_date>10.02.2019</payment_date>
                </last_payment>
                <status>blocked</status>
                <lock_date>20.02.2019</lock_date>
            </account>
        </accounts>
    </client>
    <client>
        <client_ID>987654321ZY</client_ID>
        <name>
            Jane Dough
        </name>
        <passport>MP7654321</passport>
        <login>janeDOUGH</login>
        <password>54321</password>
        <accounts>
            <account>
                <account_ID>987654321</account_ID>
                <authorization_code>4321</authorization_code>
                <account_balance>15000</account_balance>
                <currency>EUR</currency>
                <last_replenishment>
                    <replenishment_amount>2500</replenishment_amount>
                    <replenishment_date>15.01.2019</replenishment_date>
                </last_replenishment>
                <last_payment>
                    <payment_amount>1500</payment_amount>
                    <payment_date>15.02.2019</payment_date>
                </last_payment>
                <status>active</status>
                <lock_date>-</lock_date>
            </account>
        </accounts>
    </client>
</clients>
