=== Khmelov/JD2018-12-10/src/by/it/subach/jd02_07/users.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://jd02.subach.it/somestring"
        xmlns:mytype="http://jd02.subach.it/somestring"
        elementFormDefault="qualified"
        >
    <element name="users">
        <complexType>
            <sequence>
                <element
                    name="user"
                    type="mytype:typeforuser"
                    minOccurs="1"
                    maxOccurs="unbounded"   />

            </sequence>
        </complexType>
    </element>

    <complexType name="typeforuser">
        <sequence>
            <element name="login" type="ID" />
            <element name="email" type="string" />
            <element name="password" type="string" />
            <element name="ads" type="mytype:typeads" />
        </sequence>
    </complexType>

    <complexType name="typeads">
        <sequence>
            <element name="ad"
                     minOccurs="1"
                     maxOccurs="unbounded"
                     type="mytype:typead"/>
        </sequence>
    </complexType>

    <complexType name="typead">
        <all>
            <element name="description" type="string" />
            <element name="adress" type="string" />
            <element name="floor" type="positiveInteger" />
            <element name="rooms" type="positiveInteger" />
            <element name="price" type="positiveInteger" />
            <element name="area" type="positiveInteger" />
        </all>
    </complexType>
</schema>

=== Khmelov/JD2018-12-10/src/by/it/subach/jd02_07/users_plus_xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<users  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://jd02.subach.it/somestring"
        xsi:schemaLocation="http://jd02.subach.it/somestring users.xsd"
>
        <user>
            <login>VasyaP</login>
            <email>VasyaP@mail.ru</email>
            <password>qwerty</password>
            <ads>
                <ad>
                    <description>
                        Good apartments
                    </description>
                    <adress>
                        Lenina, 1
                    </adress>
                    <floor>2</floor>
                    <rooms>3</rooms>
                    <price>9999</price>
                    <area>69</area>
                </ad>
                <ad>
                    <description>
                        Small apartments
                    </description>
                    <adress>
                        Khalturina, 15
                    </adress>
                    <floor>1</floor>
                    <rooms>1</rooms>
                    <price>5555</price>
                    <area>29</area>
                </ad>
            </ads>
        </user>
        <user>
            <login>PetyaV</login>
            <email>PetyaV@mail.ru</email>
            <password>asdfgh</password>
            <ads>
                <ad>
                    <description>
                        New apartments
                    </description>
                    <adress>
                        Kirova, 3
                    </adress>
                    <floor>10</floor>
                    <rooms>5</rooms>
                    <price>1200000</price>
                    <area>150</area>
                </ad>
            </ads>
        </user>

    </users>
