=== Khmelov/JD2018-12-10/src/by/it/a_khmelev/jd02_07/users+att.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://jd02.akhmelev.by.it/somestring+att"
        xmlns:tag="http://jd02.akhmelev.by.it/somestring+att"
        elementFormDefault="qualified"
>
<element name="users" >
    <complexType>
        <sequence>
            <element
                    name="user"
                    type="tag:User"
                    minOccurs="2"
                    maxOccurs="unbounded" >
            </element>
        </sequence>
    </complexType>
</element>

<complexType name="User">
    <sequence>
        <element name="login" type="ID" />
        <element name="email" type="string" />
        <element name="password" type="string" />
        <element name="ads"  type="tag:Ads"/>
    </sequence>
    <attribute name="nickname" type="string" use="required"/>
</complexType>

<complexType name="Ads">
    <sequence>
        <element name="ad"
                 minOccurs="0"
                 maxOccurs="unbounded"
                 type="tag:Ad"/>
    </sequence>
    <attribute name="maxcount" type="positiveInteger" use="required"/>
</complexType>

<complexType name="Ad">
    <sequence>
        <element name="description" type="string"/>
        <element name="address" type="string"/>
        <element name="floor" type="integer"/>
        <element name="floors" type="positiveInteger"/>
        <element name="rooms" type="positiveInteger"/>
        <element name="price" type="tag:Price"/>
        <element name="area" type="double"/>
    </sequence>
</complexType>

<complexType name="Price">
    <simpleContent>
        <restriction base="double">
            <attribute name="currency" type="string"/>
        </restriction>
    </simpleContent>
</complexType>


</schema>

=== Khmelov/JD2018-12-10/src/by/it/a_khmelev/jd02_07/users+att+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<users  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://jd02.akhmelev.by.it/somestring+att"
        xsi:schemaLocation="http://jd02.akhmelev.by.it/somestring+att users+att.xsd"
>
    <user nickname="Vasissualy">
        <login>vasyaP</login>
        <email>vasyap@mail.ru</email>
        <password>qwerty</password>
        <ads maxcount="100">
            <ad>
                <description>
                    Good Appartments
                </description>
                <address>
                    Minsk Lenina 12 app. 25
                </address>
                <floor>2</floor>
                <floors>6</floors>
                <rooms>3</rooms>
                <price currency="б.р.">199999.0</price>
                <area>59.9</area>
            </ad>
            <ad>
                <description>
                    Small House
                </description>
                <address>
                    Minsk Khalturina 15
                </address>
                <floor>1</floor>
                <floors>2</floors>
                <rooms>4</rooms>
                <price currency="p.">8888888.0</price>
                <area>66.6</area>
            </ad>
        </ads>
    </user>
    <user  nickname="Petrusik">
        <login>petyaB</login>
        <email>petyab@mail.ru</email>
        <password>asdfgh</password>
        <ads maxcount="100">
            <ad>
                <description>
                    New Appartments
                </description>
                <address>
                    Minsk Scryganava 3 app. 125
                </address>
                <floor>7</floor>
                <floors>25</floors>
                <rooms>2</rooms>
                <price currency="$">120000.0</price>
                <area>60</area>
            </ad>
        </ads>
    </user>
</users>
