=== Khmelov/JD2018-12-10/src/by/it/a_khmelev/jd02_07/users.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT users (user)+>
<!ELEMENT user (login,email,password,ads)>
<!ELEMENT login (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT ads (ad)+>
<!ELEMENT ad (
        description, address,
        floor, floors, rooms,
        price,area)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT address (#PCDATA)>
        <!ELEMENT floor (#PCDATA)>
        <!ELEMENT floors (#PCDATA)>
        <!ELEMENT rooms (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT area (#PCDATA)>

=== Khmelov/JD2018-12-10/src/by/it/titkovskaya/jd02/jd02_07/users_real_estate/users+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE users SYSTEM
        "C:\Users\Airina\Documents\java development\JD2018-12-10\src\by\it\titkovskaya\jd02_07\users_real_estate\users.dtd" >
<users>
    <user>
        <login>vasyaP</login>
        <email>vasyap@mail.ru</email>
        <password>qwerty</password>
        <ads>
            <ad>
                <description>
                    Good Apartments
                </description>
                <address>
                    Minsk Lenina 12 app. 25
                </address>
                <floor>2</floor>
                <floors>6</floors>
                <rooms>3</rooms>
                <price>99999.0</price>
                <area>59.9</area>
            </ad>
            <ad>
                <description>
                    Small House
                </description>
                <address>
                    Minsk Lugavaya 5
                </address>
                <floor>1</floor>
                <floors>2</floors>
                <rooms>4</rooms>
                <price>88888.0</price>
                <area>66.6</area>
            </ad>
        </ads>
    </user>
    <user>
        <login>petyaB</login>
        <email>petyab@mail.ru</email>
        <password>asdfgh</password>
        <ads>
            <ad>
                <description>
                    New Apartments
                </description>
                <address>
                    Minsk Skryganova 3 app.125
                </address>
                <floor>7</floor>
                <floors>25</floors>
                <rooms>2</rooms>
                <price>120000.0</price>
                <area>60</area>
            </ad>
        </ads>
    </user>
</users>
