=== Khmelov/JD2018-12-10/src/by/it/migunko/jd02_07/travels.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT Travels (Travel)+>
        <!ELEMENT Travel (Login, Password, Email, TravelTours)>
        <!ELEMENT Login (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT TravelTours (TravelTour)+>
        <!ELEMENT TravelTour ( TypeOfTravel, Destination, Hotel,  CountOfNight, Price)>
        <!ELEMENT TypeOfTravel (#PCDATA)>
        <!ELEMENT Destination (#PCDATA)>
        <!ELEMENT Hotel (#PCDATA)>
        <!ELEMENT CountOfNight (#PCDATA)>
        <!ELEMENT Price (#PCDATA)>

=== Khmelov/JD2018-12-10/src/by/it/migunko/jd02_07/travels+dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Travels SYSTEM "travels.dtd">
<Travels>
    <Travel>
        <Login>Evgeniya</Login>
        <Password>jkaljflk</Password>
        <Email>Evgeniya@gmail.com</Email>
        <TravelTours>
            <TravelTour>
                <TypeOfTravel>Holiday</TypeOfTravel>
                <Destination>Кипр</Destination>
                <Hotel>Petsas Apartments</Hotel>
                <CountOfNight>7</CountOfNight>
                <Price>645.0</Price>
            </TravelTour>
            <TravelTour>
                <TypeOfTravel>Excursion</TypeOfTravel>
                <Destination>Санкт-Петербург</Destination>
                <Hotel>Галунов Отель</Hotel>
                <CountOfNight>2</CountOfNight>
                <Price>215.0</Price>
            </TravelTour>
        </TravelTours>
    </Travel>
    <Travel>
        <Login>Maria</Login>
        <Password>afvaf</Password>
        <Email>Maria@gmail.com</Email>
        <TravelTours>
            <TravelTour>
                <TypeOfTravel>Holidayr</TypeOfTravel>
                <Destination>Париж</Destination>
                <Hotel>Relais Du Louvre</Hotel>
                <CountOfNight>7</CountOfNight>
                <Price>500.0</Price>
            </TravelTour>
        </TravelTours>
    </Travel>
</Travels>
